const questions = [
  "Den mest äckliga (hygen) i gruppen",
  "Den som högst troligen har blöttat sängen senaste året",
  "Den som skulle låta sin fru/guzz vara dominant",
  "Den som är drängigaste",  
  "Framtida arbetslös",
  "Om du skulle välja en person som skulle försvina från ditt liv från FortniteOGs, vem skulle det vara?",
  "Den som inte borde vara med i vängruppen",
  "Den som högst troligen kommer blocka sina vänner efter gymnasiet",
  "Gruppens drama-queen",
  "Den du minst vibar/gillar i gruppen",
  "Din skolvän (kompisar bara i skolan)",
  "Den du inte vill hänga med efter skolan",
  "Den som är mest freaky",
  "Den som kommer 'escape the matrix', men kommer vara utanför ICA/Lidel och be om pengar",
  "Personen som skulle vara ner på två knä och skrika 'woof woof' för sin guzz",
  "Personen som skulle välja sin guzz över morsan",
  "Gruppens nonchalant-wanna be",
  "Den som kommer klaga mest under student resan",
  "Den som skulle stå i kö till Bonnie Blue bussen",
  "Grupens main-character",
  "Gruppens bögiga",
  "Gruppens fetta gött",
  "Den mest cringie personen här",
  "En pesron som borde söka hjälp (mentalt)!",
  "Personen som har minst respekt för andra",
  "Den helt efterblivna i gruppen",
  "Gruppens hemlösa (klädstilen är bajs)",
  "Den du minst vill ha hemma hos dig (gäst)",
  "Personen med igen framtid",
  "En person som skrämmer bort guzzarna",
  "Personen som har för höga standardad, utifrån utseande",
  "Personen som har för höga standardad, utifrån personlighet",
  "Personen som behöver ta sitt liv seriöst snart",
  "Den som är 'mamas boy'",
  "Den som har minst moral och medkännsla",
  "Person som skulle begå mord för pengar",
  "Personen som behöver söka gud",
  "Personen du inte bryr dig mycket om",
  "Personen som behöver fixa håret, för den är BAJS",
  "Personen som mest sanolikgt skulle yapp en får",
  "Personen som har FÖR mycket luft!",
  "Personen som har skit äklig ande dräckt",
  "Personen som behöver gå till gymet",
  "Personen med största näsan",
  "Personen med för mycket ego",
  "Personen med 'big dick' energi",
  "Gruppens hora (skule kunna ligga med allt och alla)",
  "Den som har gjort 'ragebait' till sin personlighet",
  "Personen som är lite för delusional",
  "Den snyggaste i gruppen",
  "Den med helt okej personlighet",
  "Den som skulle kunna vara dagen 'hitler'",
  "Den som faktikt har en framtid",
  "Pick-me i gruppen",
  "Den som kommer fk up sin marrige",
  "Den som skulle batala för en happy ending",
  "Gruppens 'clown'",
  "Den som skulle lätt bli dömd för SA (sexual asult)",
  "Den som skulle vara dålig i sängen",
  "Den som skulle kunna hittas i PornHub om 10 år",
  "Den som behöver ta det lungt",
  "Den som klagar för mycket",
  "Den som tror alla vill ha han/hon",
  "Den sveniferade i gruppen",
  "Leker för mycket",
  "Den som skulle halka på en bannan",
  "Den som använder folk för sin egna nyttja",
  "Gruppens dubbel-moral",
  "Den snåla personen",
  "Den som skulle bråka med sina föräldrar för en tjej",
  "Den som behöver elda upp sig själv :)",
  "Den som är por-holic (beroande av porn)",
];

function getRandomQuestion() {
  return questions[Math.floor(Math.random() * questions.length)];
}
function getRandomOutcome() {
  return Math.random() < 0.3 ? "berätta" : "skipp";
}